version = 1
SPDX-PackageName = "Myna"
SPDX-PackageSupplier = "Neptuwunium <ada@chronovore.dev>"
SPDX-PackageDownloadLocation = ["https://git.kimapr.net/neptuwunium/myna", "https://github.com/neptuwunium/myna"]
annotations = []
